### ISSUE TITLE
[9.0/10.0] Feature Request - Website Shipping Rates

### ISSUE THREAD

**Issue by lukebranch** [LasLabs/odoo-connector-easypost#3]
@lasley ,

Thanks for building this connector! I was looking into building something like this myself one day with another shipping API, however it looks like yours will be the better option.

I have a customer project that I will need to allow shipping methods to be selected on the website by the customer (eg. UPS expedited), and then allow me one of two options per shipping provider:

Option 1) auto-assign a tracking number according to customer-selected shipping method and print out a shipping label using report-print-send to a specific label printer (second part I can handle with automated actions)
Option 2) allow for manual selection of shipping method and manual printing of shipping label

I'd like to know if there are any plans to build another module that handles this type of behaviour, and if not I would like to propose that I provide at least a partial funding of development for a module that handles this kind of behaviour for use with my customer's project.

Please let me know if this is something you're open to discussing.

**Comment by lasley** [comment]
@lukebranch - Option 1 is our ideal scenario as well, although the website side is pretty much the last on the chopping block with our current plans.

What kind of time frame were you looking at?

**Comment by lukebranch** [comment]
@lasley ,

Thanks for the reply. The customer is not in a huge rush as they have been living without it for quite a while, however it is something they would like to implement in the near future to improve their warehouse team's efficiency.

If we were able to get our hands on a functional set of modules to handle option one (even if it's not fully production ready) in around 2 months or so I think this would be the ideal timeframe.

Please let me know if funding would help in this regard, and if so how much would be required to fully fund getting to option one, and i'll discuss with the customer and get back to you to see if we can cover the whole amount, or partial amount and try to organise other funding from other sources to help.

**Comment by lasley** [comment]
@t3ddftw - Some of this is in the underlying pack dependencies you have been working on. Care to comment on the viability of the automation, particularly in terms of weights?

**Comment by tedsalmon** [comment]
@lasley,

There should be no issues with automation with these packaging modules. In fact, the extension of `stock.quant.package` already provides some calculations of package weight(s) based on the packaging and products inside.

Thanks!

**Comment by lukebranch** [comment]
good to know, thanks. Let me know if there's anything else you'd like to discuss in the meantime regarding this project.

**Comment by lukebranch** [comment]
I've just taken a look at the runbots for:

LABS-158-create-easypost-tracker
LABS-322-connector-easypost-bugs

and it looks like there has been a huge amount of progress made on the easypost connector since I last checked.

Please let me know if there is an opportunity to contribute some funding to the project. I would like to discuss this with a customer who is keen to implement these features after discussing the odoo-connector-easypost feature set with them.

**Comment by lasley** [comment]
@lukebranch - Send me an email (in my GH profile) and we can discuss funding & the specific feature-sets your customer needs.

**Comment by lukebranch** [comment]
@lasley ,

Thanks for the reply, and my apologies for not replying sooner, i've only just seen this message. I'll send you through an email this afternoon.

**Comment by lukebranch** [comment]
@lasley ,

FYI - it looks like easypost integration is coming to 11.0e:
<img src="https://cloud.githubusercontent.com/assets/2337666/22830004/fd78fae0-efdf-11e6-8fbd-a69c13d4c729.png"/>

**Comment by lasley** [comment]
@lukebranch Hahaha nice, although I bet it's an EE only feature. EE is not part of my PaaS, so you'll see me making a lot of modules competing with core Odoo. Admittedly I would consider providing EE, but I'm not willing to pay Odoo SA for the "opportunity" to sell their enterprise product. 

Also, I completely spaced telling you - we finished with [`delivery_sale_rate`](https://github.com/OCA/stock-logistics-workflow/pull/297) for v9, which provides the necessary link between the sales shipping rates & the connectors. Easypost connector should now be website compatible with that module installed. Let us know if that's not the case!

**Comment by lukebranch** [comment]
@lasley , yeah, it's only an EE feature for sure, it's not in any of the community dev branches. 

Thanks for the heads up about the delivery_sale_rate, that's awesome news! I'm going to test the new module(s) out this week and i'll get back to you if I run into any issues with using them on the website.

**Comment by lasley** [comment]
Exists in #122, closing. Please let us know if the module combination misses a featureset.
